<?php
//WORDPRESS ENGINE, YOU CAN ADD CUSTOM COMMAND ACCEPTED BY WORDPRESS
$WP_PATH=$GLOBALS["wppath"]="../"; //PATH TO WORDPRESS BASE DIRECTORY
define('WP_USE_THEMES', false);
@require($WP_PATH."wp-blog-header.php"); //STARTING ENGINE
?>